export const books = [
    {
        "id": "BK001",
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "description": "A shocking psychological thriller about a woman who shoots her husband and the psychotherapist who is determined to unravel what happened.",
        "cover_image": "https://m.media-amazon.com/images/I/81JJPDNlxSL._UF1000,1000_QL80_.jpg",
        "price": 499.00,
        "category": "Thriller",
        "rating": 4.7,
        "isbn": "9781250301697"
    },
    {
        "id": "BK002",
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "description": "A captivating coming-of-age story interwoven with a murder mystery, set in the isolated marshes of North Carolina.",
        "cover_image": "https://m.media-amazon.com/images/I/81e+mSqZvnL.jpg",
        "price": 399.00,
        "category": "Fiction",
        "rating": 4.4,
        "isbn": "9780735219106"
    },
    {
        "id": "BK003",
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "description": "An astronaut wakes up on a spaceship with no memory of who he is or how he got there, tasked with saving humanity from an interstellar catastrophe.",
        "cover_image": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1597695864l/54493401.jpg",
        "price": 599.00,
        "category": "Sci-Fi",
        "rating": 4.8,
        "isbn": "9780593395561"
    },
    {
        "id": "BK004",
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "description": "Nora Seed gets a chance to try out different lives she could have lived, exploring regrets and what truly makes a life fulfilling.",
        "cover_image": "https://m.media-amazon.com/images/I/81J6APjwxlL.jpg",
        "price": 349.00,
        "category": "Fantasy",
        "rating": 3.6,
        "isbn": "9780525559474"
    },
    {
        "id": "BK005",
        "title": "Educated",
        "author": "Tara Westover",
        "description": "An unforgettable memoir about a young girl who, kept out of school by her survivalist family, educates herself and eventually earns a PhD from Cambridge University.",
        "cover_image": "https://m.media-amazon.com/images/I/71-4MkLN5jL.jpg",
        "price": 449.00,
        "category": "Memoir",
        "rating": 4.6,
        "isbn": "9780399590504"
    },
    {
        "id": "BK006",
        "title": "The Henna Artist",
        "author": "Alka Joshi",
        "description": "Set in 1950s India, a young woman escapes an abusive marriage and becomes a renowned henna artist to the elite of Jaipur.",
        "cover_image": "https://m.media-amazon.com/images/I/914ziL+fEcL._UF1000,1000_QL80_.jpg",
        "price": 499.00,
        "category": "Historical Fiction",
        "rating": 4.3,
        "isbn": "9780778309451"
    },
    {
        "id": "BK007",
        "title": "Circe",
        "author": "Madeline Miller",
        "description": "A feminist retelling of the Greek myth of Circe, the goddess of magic, as she navigates power, love, and loneliness.",
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1565909496i/35959740.jpg",
        "price": 399.00,
        "category": "Mythology",
        "rating": 4.5,
        "isbn": "9780316556347" 
    },
    {
        "id": "BK008",
        "title": "Becoming",
        "author": "Michelle Obama",
        "description": "A memoir by former First Lady Michelle Obama, sharing her life story from her childhood in Chicago to her years in the White House.",
        "cover_image": "https://m.media-amazon.com/images/I/81KGjsBXQ7L._UF1000,1000_QL80_.jpg",
        "price": 699.00,
        "category": "Memoir",
        "rating": 4.8,
        "isbn": "9781524763138"
    },
    {
        "id": "BK009",
        "title": "The Guest List",
        "author": "Lucy Foley",
        "description": "A wedding on a remote island off the coast of Ireland turns deadly when a body is discovered, and everyone is a suspect.",
        "cover_image": "https://m.media-amazon.com/images/I/81QEpeAxCxS._UF1000,1000_QL80_.jpg",
        "price": 429.00,
        "category": "Mystery",
        "rating": 4.2,
        "isbn": "9780062868930"
    },
    {
        "id": "BK010",
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "An easy and proven way to build good habits and break bad ones, offering practical strategies for continuous improvement.",
        "cover_image": "https://m.media-amazon.com/images/I/81F90H7hnML.jpg",
        "price": 499.00,
        "category": "Self-Help",
        "rating": 4.8,
        "isbn": "9780735211292"
    },
    {
        "id": "BK011",
        "title": "The Four Agreements",
        "author": "Don Miguel Ruiz",
        "description": "A practical guide to personal freedom and happiness, based on ancient Toltec wisdom.",
        "cover_image": "https://m.media-amazon.com/images/I/913A1+rl-gL._UF1000,1000_QL80_.jpg",
        "price": 329.00,
        "category": "Philosophy",
        "rating": 4.3,
        "isbn": "9781878424310"
    },
    {
        "id": "BK012",
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "description": "Explores the entire history of humanity, from the first humans to radical scientific advances.",
        "cover_image": "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
        "price": 649.00,
        "category": "History",
        "rating": 4.7,
        "isbn": "9780062316110"
    },
    {
        "id": "BK013",
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "description": "A philosophical novel about a shepherd boy who journeys in search of a hidden treasure.",
        "cover_image": "https://m.media-amazon.com/images/I/617lxveUjYL.jpg",
        "price": 379.00,
        "category": "Fiction",
        "rating": 4.6,
        "isbn": "9780062315007"
    },
    {
        "id": "BK014",
        "title": "Dune",
        "author": "Frank Herbert",
        "description": "Set in the distant future, a thrilling science fiction epic of a desert planet and messianic destiny.",
        "cover_image": "https://m.media-amazon.com/images/I/81Ua99CURsL.jpg",
        "price": 549.00,
        "category": "Sci-Fi",
        "rating": 4.4,
        "isbn": "9780441172719"
    },
    {
        "id": "BK015",
        "title": "The Da Vinci Code",
        "author": "Dan Brown",
        "description": "A symbologist and cryptologist investigate a murder in the Louvre uncovering a religious mystery.",
        "cover_image": "https://m.media-amazon.com/images/I/71y4X5150dL.jpg",
        "price": 429.00,
        "category": "Thriller",
        "rating": 4.5,
        "isbn": "9780552161275"
    },
    {
        "id": "BK016",
        "title": "1984",
        "author": "George Orwell",
        "description": "A dystopian novel and cautionary tale about totalitarianism and surveillance.",
        "cover_image": "https://m.media-amazon.com/images/I/71wANojhEKL.jpg",
        "price": 299.00,
        "category": "Dystopian",
        "rating": 4.6,
        "isbn": "9780451524935"
    },
    {
        "id": "BK017",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "description": "A story about racial injustice and the loss of innocence in the American South.",
        "cover_image": "https://m.media-amazon.com/images/I/81gepf1eMqL._UF1000,1000_QL80_.jpg",
        "price": 319.00,
        "category": "Classic",
        "rating": 4.9,
        "isbn": "9780061120084"
    },
    {
        "id": "BK018",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "description": "A classic novel exploring themes of wealth, love, and the American Dream.",
        "cover_image": "https://m.media-amazon.com/images/I/81TLiZrasVL._UF1000,1000_QL80_.jpg",
        "price": 279.00,
        "category": "Classic",
        "rating": 4.3,
        "isbn": "9780743273565"
    },
    {
        "id": "BK019",
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "description": "A dystopian vision of a technologically advanced future controlled by conditioning.",
        "cover_image": "https://m.media-amazon.com/images/I/91KqWgAmufL._UF1000,1000_QL80_.jpg",
        "price": 299.00,
        "category": "Dystopian",
        "rating": 4.4,
        "isbn": "9780060929871"
    },
    {
        "id": "BK020",
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "description": "A fantasy adventure following Bilbo Baggins on an unexpected journey.",
        "cover_image": "https://m.media-amazon.com/images/I/81mCE+uclxL._UF1000,1000_QL80_.jpg",
        "price": 449.00,
        "category": "Fantasy",
        "rating": 4.8,
        "isbn": "9780547928227"
    },
    {
        "id": "BK021",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "description": "A romantic novel that critiques the British class system of the early 19th century.",
        "cover_image": "https://m.media-amazon.com/images/I/712P0p5cXIL._UF1000,1000_QL80_.jpg",
        "price": 349.00,
        "category": "Romance",
        "rating": 4.6,
        "isbn": "9780141439518" 
    },
    {
        "id": "BK022",
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "description": "A novel about teenage rebellion and existential disillusionment.",
        "cover_image": "https://m.media-amazon.com/images/I/8125BDk3l9L.jpg",
        "price": 329.00,
        "category": "Fiction",
        "rating": 3.8,
        "isbn": "9780241950425"
    },
    {
        "id": "BK023",
        "title": "The Road",
        "author": "Cormac McCarthy",
        "description": "A post-apocalyptic journey of a father and son across a barren America.",
        "cover_image": "https://m.media-amazon.com/images/I/51M7XGLQTBL.jpg",
        "price": 399.00,
        "category": "Dystopian",
        "rating": 4.2,
        "isbn": "9780330513005"
    },
    {
        "id": "BK024",
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "description": "A psychological thriller about a missing woman and a suspicious husband.",
        "cover_image": "https://m.media-amazon.com/images/I/71+khXHbe5L.jpg",
        "price": 499.00,
        "category": "Thriller",
        "rating": 4.5,
        "isbn": "9780307588364"
    },
    {
        "id": "BK025",
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "description": "This hauntingly beautiful novel unravels a tale of forbidden love, revenge, and tumultuous emotions as captivating characters navigate the wild moors of 19th-century Yorkshire.",
        "cover_image": "https://d28hgpri8am2if.cloudfront.net/tagged_assets/cvr9781471141638/9781471141638_hr.jpg",
        "price": 479.00,
        "category": "Tragedy",
        "rating": 4.9,
        "isbn": "9780141439556"
    },
    {
        "id": "BK026",
        "title": "The Martian",
        "author": "Andy Weir",
        "description": "An astronaut stranded on Mars must use ingenuity to survive.",
        "cover_image": "https://m.media-amazon.com/images/I/71Tp86ptAtL._UF1000,1000_QL80_.jpg",
        "price": 459.00,
        "category": "Sci-Fi",
        "rating": 4.7,
        "isbn": "9780804139021"
    },
    {
        "id": "BK027",
        "title": "Kafka on the Shore",
        "author": "Haruki Murakami",
        "description": "A surreal novel blending reality and metaphysical elements.",
        "cover_image": "https://m.media-amazon.com/images/I/81tdbrewW0L.jpg",
        "price": 549.00,
        "category": "Philosophy",
        "rating": 4.2,
        "isbn": "9781400043668"
    },
    {
        "id": "BK028",
        "title": "Life of Pi",
        "author": "Yann Martel",
        "description": "A survival tale of a boy stranded on a lifeboat with a tiger.",
        "cover_image": "https://m.media-amazon.com/images/I/71wW1coSR0L.jpg",
        "price": 379.00,
        "category": "Adventure",
        "rating": 4.4,
        "isbn": "9780857865533"
    },
    {
        "id": "BK029",
        "title": "American Gods",
        "author": "Neil Gaiman",
        "description": "A fantasy novel about old gods clashing with new in modern America.",
        "cover_image": "https://m.media-amazon.com/images/I/716LpMKQ3iL._UF1000,1000_QL80_.jpg",
        "price": 589.00,
        "category": "Fantasy",
        "rating": 4.3,
        "isbn": "9780755322817"
    },
    {
        "id": "BK030",
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "description": "A comprehensive biography of Steve Jobs, capturing his passion, intensity, and revolutionary impact on technology and design.",
        "cover_image": "https://m.media-amazon.com/images/I/81NSb9Jy0HL.jpg",
        "price": 549.00,
        "category": "Biography",
        "rating": 4.6,
        "isbn": "9780349140438"
    }
];